### ISSUE TITLE
Multithreading issues

### ISSUE THREAD

**Issue by funny-falcon** [craigmj/gophia#1]
Sophia does not support access to one database from multiple threads.
So that, it should be mentioned in a gophia's docs, that it is not safe to use one database from several concurent goroutines, especially if GOMAXPROCS>1.
(perhaps, it is safe if GOMAXPROCS==1, no sure for this case)

**Comment by pmwkaa** [comment]
sorry guys for that, i promise to fix it asap when i get time :) Thanks!

**Comment by funny-falcon** [comment]
I really not sure, should it be fixed at gophia level, but it should be mentioned in documentation, that access should be synchronized either using separate working goroutine and channels or simply locking mutex.
